[package]
name = "minishogilib"
version = "0.0.3"
authors = ["nakayashiki <tnakayashiki01@gmail.com>"]

[lib]
name = "minishogilib"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.7.0"
features = []

[dependencies]
rand = "0.6"
